spring:
  messages:
    basename: i18n/language
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_music?serverTimezone=UTC
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    username: zhuoj127@163.com
    password: QPYJCZAHODHTNTBT
    default-encoding: UTF-8
